"""Shared model hyperparameters and preset helpers."""

from typing import Any, Mapping

SUPPORTED_ARCHITECTURES = (
    "gru",
    "tcn",
    "lstm_hybrid",
    "online_spatialnet",
    "stereo_lite",
    "stereo_stacked_lstm",
    "stereo_beam_lite",
)

MODEL_SCALE_PRESETS = {
    # Legacy GRU baselines (kept for backward compatibility).
    "legacy_small": {
        "architecture": "gru",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 128,
        "num_layers": 2,
        "dropout": 0.0,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 1,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "legacy_base": {
        "architecture": "gru",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 256,
        "num_layers": 3,
        "dropout": 0.1,
        "post_ffn_blocks": 2,
        "ffn_expansion": 4,
        "mask_hidden_size": 256,
        "mask_head_layers": 2,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 384,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    # Optional TCN presets for ablation.
    "tcn_small": {
        "architecture": "tcn",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 128,
        "num_layers": 2,
        "dropout": 0.0,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 2,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "tcn_base": {
        "architecture": "tcn",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 256,
        "num_layers": 3,
        "dropout": 0.05,
        "post_ffn_blocks": 2,
        "ffn_expansion": 4,
        "mask_hidden_size": 256,
        "mask_head_layers": 2,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 384,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    # Recommended hybrid LSTM presets (time + frequency).
    "small": {
        "architecture": "lstm_hybrid",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 128,
        "num_layers": 2,
        "dropout": 0.05,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 2,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "base": {
        "architecture": "lstm_hybrid",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 192,
        "num_layers": 3,
        "dropout": 0.08,
        "post_ffn_blocks": 2,
        "ffn_expansion": 4,
        "mask_hidden_size": 256,
        "mask_head_layers": 2,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 384,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    "large": {
        "architecture": "lstm_hybrid",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 256,
        "num_layers": 4,
        "dropout": 0.1,
        "post_ffn_blocks": 3,
        "ffn_expansion": 4,
        "mask_hidden_size": 384,
        "mask_head_layers": 2,
        "time_encoder_dim": 192,
        "time_kernel_size": 512,
        "fusion_hidden_size": 512,
        "lstm_hidden_size": 512,
        "lstm_num_layers": 4,
        "bottleneck_size": 384,
        "tcn_hidden_size": 768,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 4,
    },
    "xlarge": {
        "architecture": "lstm_hybrid",
        "n_fft": 1024,
        "hop_length": 256,
        "win_length": 1024,
        "hidden_size": 320,
        "num_layers": 4,
        "dropout": 0.1,
        "post_ffn_blocks": 4,
        "ffn_expansion": 4,
        "mask_hidden_size": 512,
        "mask_head_layers": 3,
        "time_encoder_dim": 256,
        "time_kernel_size": 1024,
        "fusion_hidden_size": 768,
        "lstm_hidden_size": 768,
        "lstm_num_layers": 4,
        "bottleneck_size": 512,
        "tcn_hidden_size": 1024,
        "tcn_kernel_size": 3,
        "tcn_blocks": 10,
        "tcn_repeats": 4,
    },
    "stereo_lite_tiny": {
        "architecture": "stereo_lite",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 96,
        "num_layers": 2,
        "dropout": 0.05,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 1,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "stereo_lite_base": {
        "architecture": "stereo_lite",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 128,
        "num_layers": 3,
        "dropout": 0.08,
        "post_ffn_blocks": 2,
        "ffn_expansion": 2,
        "mask_hidden_size": 192,
        "mask_head_layers": 1,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 256,
        "lstm_num_layers": 3,
        "bottleneck_size": 192,
        "tcn_hidden_size": 384,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 2,
    },
    "stereo_lite_large": {
        "architecture": "stereo_lite",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 160,
        "num_layers": 4,
        "dropout": 0.10,
        "post_ffn_blocks": 2,
        "ffn_expansion": 2,
        "mask_hidden_size": 256,
        "mask_head_layers": 1,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 320,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    "stereo_lstm_tiny": {
        "architecture": "stereo_stacked_lstm",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 96,
        "num_layers": 2,
        "dropout": 0.05,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 1,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "stereo_lstm_base": {
        "architecture": "stereo_stacked_lstm",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 128,
        "num_layers": 3,
        "dropout": 0.08,
        "post_ffn_blocks": 2,
        "ffn_expansion": 2,
        "mask_hidden_size": 192,
        "mask_head_layers": 1,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 256,
        "lstm_num_layers": 3,
        "bottleneck_size": 192,
        "tcn_hidden_size": 384,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 2,
    },
    "stereo_lstm_large": {
        "architecture": "stereo_stacked_lstm",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 160,
        "num_layers": 4,
        "dropout": 0.10,
        "post_ffn_blocks": 2,
        "ffn_expansion": 2,
        "mask_hidden_size": 256,
        "mask_head_layers": 1,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 320,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    "stereo_beam_tiny": {
        "architecture": "stereo_beam_lite",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 96,
        "num_layers": 2,
        "dropout": 0.05,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 1,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "stereo_beam_base": {
        "architecture": "stereo_beam_lite",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 128,
        "num_layers": 3,
        "dropout": 0.08,
        "post_ffn_blocks": 2,
        "ffn_expansion": 2,
        "mask_hidden_size": 192,
        "mask_head_layers": 1,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 256,
        "lstm_num_layers": 3,
        "bottleneck_size": 192,
        "tcn_hidden_size": 384,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 2,
    },
    "stereo_beam_large": {
        "architecture": "stereo_beam_lite",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 160,
        "num_layers": 4,
        "dropout": 0.10,
        "post_ffn_blocks": 2,
        "ffn_expansion": 2,
        "mask_hidden_size": 256,
        "mask_head_layers": 1,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 320,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    "osn_small": {
        "architecture": "online_spatialnet",
        "n_fft": 256,
        "hop_length": 128,
        "win_length": 256,
        "hidden_size": 128,
        "num_layers": 2,
        "dropout": 0.05,
        "post_ffn_blocks": 1,
        "ffn_expansion": 2,
        "mask_hidden_size": 128,
        "mask_head_layers": 2,
        "time_encoder_dim": 64,
        "time_kernel_size": 256,
        "fusion_hidden_size": 256,
        "lstm_hidden_size": 192,
        "lstm_num_layers": 2,
        "bottleneck_size": 128,
        "tcn_hidden_size": 256,
        "tcn_kernel_size": 3,
        "tcn_blocks": 6,
        "tcn_repeats": 2,
    },
    "osn_base": {
        "architecture": "online_spatialnet",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 192,
        "num_layers": 3,
        "dropout": 0.08,
        "post_ffn_blocks": 2,
        "ffn_expansion": 4,
        "mask_hidden_size": 256,
        "mask_head_layers": 2,
        "time_encoder_dim": 128,
        "time_kernel_size": 512,
        "fusion_hidden_size": 384,
        "lstm_hidden_size": 384,
        "lstm_num_layers": 3,
        "bottleneck_size": 256,
        "tcn_hidden_size": 512,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 3,
    },
    "osn_large": {
        "architecture": "online_spatialnet",
        "n_fft": 512,
        "hop_length": 128,
        "win_length": 512,
        "hidden_size": 256,
        "num_layers": 4,
        "dropout": 0.1,
        "post_ffn_blocks": 3,
        "ffn_expansion": 4,
        "mask_hidden_size": 384,
        "mask_head_layers": 2,
        "time_encoder_dim": 192,
        "time_kernel_size": 512,
        "fusion_hidden_size": 512,
        "lstm_hidden_size": 512,
        "lstm_num_layers": 4,
        "bottleneck_size": 384,
        "tcn_hidden_size": 768,
        "tcn_kernel_size": 3,
        "tcn_blocks": 8,
        "tcn_repeats": 4,
    },
}

MANUAL_MODEL_OVERRIDE_KEYS = (
    "architecture",
    "n_fft",
    "hop_length",
    "win_length",
    "hidden_size",
    "num_layers",
    "dropout",
    "post_ffn_blocks",
    "ffn_expansion",
    "mask_hidden_size",
    "mask_head_layers",
    "time_encoder_dim",
    "time_kernel_size",
    "fusion_hidden_size",
    "lstm_hidden_size",
    "lstm_num_layers",
    "bottleneck_size",
    "tcn_hidden_size",
    "tcn_kernel_size",
    "tcn_blocks",
    "tcn_repeats",
)

DEFAULT_SEPARATOR_CONFIG = {
    "num_speakers": 2,
    "n_fft": 256,
    "hop_length": 128,
    "win_length": 256,
    "architecture": "lstm_hybrid",
    "dropout": 0.0,
    "mask_hidden_size": 0,
    "mask_head_layers": 1,
    "hidden_size": 128,
    "num_layers": 2,
    "post_ffn_blocks": 1,
    "ffn_expansion": 2,
    "time_encoder_dim": 128,
    "time_kernel_size": 256,
    "fusion_hidden_size": 256,
    "lstm_hidden_size": 256,
    "lstm_num_layers": 3,
    "bottleneck_size": 256,
    "tcn_hidden_size": 512,
    "tcn_kernel_size": 3,
    "tcn_blocks": 8,
    "tcn_repeats": 2,
    "stereo_frontend_dim": 48,
    "stereo_frontend_layers": 2,
    "stereo_band_kernel_size": 7,
    "use_learned_stereo_fusion": True,
    "use_azimuth_conditioning": True,
    "default_left_azimuth_deg": -15.0,
    "default_right_azimuth_deg": 15.0,
    "osn_num_layers": 8,
    "osn_dim_hidden": 96,
    "osn_dim_ffn": 192,
    "osn_dim_squeeze": 8,
    "osn_num_heads": 4,
    "osn_encoder_kernel_size": 5,
    "osn_freq_kernel_size": 5,
    "osn_time_kernel_size": 3,
    "osn_freq_conv_groups": 8,
    "osn_time_conv_groups": 8,
    "osn_attention_scope": 251,
    "osn_attention": "ret(2,share_qk)",
    "osn_streaming_history": 320,
    "force_rnn_fp32": True,
}


def normalize_architecture_name(architecture: Any) -> str:
    name = str(architecture or "lstm_hybrid").lower()
    if name == "lstm":
        return "lstm_hybrid"
    return name


def _as_bool(value: Any) -> bool:
    if isinstance(value, str):
        return value.strip().lower() not in {"", "0", "false", "no", "off"}
    return bool(value)


def validate_model_hparams(hparams: Mapping[str, Any]) -> None:
    arch = normalize_architecture_name(hparams.get("architecture", ""))
    if arch not in SUPPORTED_ARCHITECTURES:
        raise ValueError(
            "architecture must be one of "
            f"{'/'.join(SUPPORTED_ARCHITECTURES)}, got: {hparams.get('architecture')}"
        )
    if int(hparams["hop_length"]) > int(hparams["win_length"]):
        raise ValueError("hop_length must be <= win_length")
    if int(hparams["n_fft"]) < int(hparams["win_length"]):
        raise ValueError("n_fft should be >= win_length")
    if arch == "tcn":
        if int(hparams["tcn_blocks"]) < 1:
            raise ValueError("tcn_blocks must be >= 1")
        if int(hparams["tcn_repeats"]) < 1:
            raise ValueError("tcn_repeats must be >= 1")
        if int(hparams["tcn_kernel_size"]) < 2:
            raise ValueError("tcn_kernel_size must be >= 2")
    if arch == "lstm_hybrid":
        if int(hparams["lstm_num_layers"]) < 1:
            raise ValueError("lstm_num_layers must be >= 1")
        if int(hparams["lstm_hidden_size"]) < 1:
            raise ValueError("lstm_hidden_size must be >= 1")
        if int(hparams["time_encoder_dim"]) < 1:
            raise ValueError("time_encoder_dim must be >= 1")
        if int(hparams["time_kernel_size"]) < 1:
            raise ValueError("time_kernel_size must be >= 1")
        if int(hparams["fusion_hidden_size"]) < 1:
            raise ValueError("fusion_hidden_size must be >= 1")
    if arch in {"stereo_lite", "stereo_stacked_lstm", "stereo_beam_lite"}:
        if int(hparams["hidden_size"]) < 32:
            raise ValueError(f"hidden_size must be >= 32 for {arch}")
        if int(hparams["num_layers"]) < 1:
            raise ValueError(f"num_layers must be >= 1 for {arch}")


def separator_kwargs_from_config(cfg: Mapping[str, Any]) -> dict:
    merged = dict(DEFAULT_SEPARATOR_CONFIG)
    for key in DEFAULT_SEPARATOR_CONFIG:
        if key in cfg and cfg[key] is not None:
            merged[key] = cfg[key]
    merged["architecture"] = normalize_architecture_name(merged["architecture"])
    return {
        "num_speakers": int(merged["num_speakers"]),
        "n_fft": int(merged["n_fft"]),
        "hop_length": int(merged["hop_length"]),
        "win_length": int(merged["win_length"]),
        "architecture": merged["architecture"],
        "dropout": float(merged["dropout"]),
        "mask_hidden_size": int(merged["mask_hidden_size"]),
        "mask_head_layers": int(merged["mask_head_layers"]),
        "hidden_size": int(merged["hidden_size"]),
        "num_layers": int(merged["num_layers"]),
        "post_ffn_blocks": int(merged["post_ffn_blocks"]),
        "ffn_expansion": int(merged["ffn_expansion"]),
        "time_encoder_dim": int(merged["time_encoder_dim"]),
        "time_kernel_size": int(merged["time_kernel_size"]),
        "fusion_hidden_size": int(merged["fusion_hidden_size"]),
        "lstm_hidden_size": int(merged["lstm_hidden_size"]),
        "lstm_num_layers": int(merged["lstm_num_layers"]),
        "bottleneck_size": int(merged["bottleneck_size"]),
        "tcn_hidden_size": int(merged["tcn_hidden_size"]),
        "tcn_kernel_size": int(merged["tcn_kernel_size"]),
        "tcn_blocks": int(merged["tcn_blocks"]),
        "tcn_repeats": int(merged["tcn_repeats"]),
        "stereo_frontend_dim": int(merged["stereo_frontend_dim"]),
        "stereo_frontend_layers": int(merged["stereo_frontend_layers"]),
        "stereo_band_kernel_size": int(merged["stereo_band_kernel_size"]),
        "use_learned_stereo_fusion": _as_bool(merged["use_learned_stereo_fusion"]),
        "use_azimuth_conditioning": _as_bool(merged["use_azimuth_conditioning"]),
        "default_left_azimuth_deg": float(merged["default_left_azimuth_deg"]),
        "default_right_azimuth_deg": float(merged["default_right_azimuth_deg"]),
        "osn_num_layers": int(merged["osn_num_layers"]),
        "osn_dim_hidden": int(merged["osn_dim_hidden"]),
        "osn_dim_ffn": int(merged["osn_dim_ffn"]),
        "osn_dim_squeeze": int(merged["osn_dim_squeeze"]),
        "osn_num_heads": int(merged["osn_num_heads"]),
        "osn_encoder_kernel_size": int(merged["osn_encoder_kernel_size"]),
        "osn_freq_kernel_size": int(merged["osn_freq_kernel_size"]),
        "osn_time_kernel_size": int(merged["osn_time_kernel_size"]),
        "osn_freq_conv_groups": int(merged["osn_freq_conv_groups"]),
        "osn_time_conv_groups": int(merged["osn_time_conv_groups"]),
        "osn_attention_scope": int(merged["osn_attention_scope"]),
        "osn_attention": str(merged["osn_attention"]),
        "osn_streaming_history": int(merged["osn_streaming_history"]),
        "force_rnn_fp32": _as_bool(merged["force_rnn_fp32"]),
    }
